services:

  db:
    image: 'postgres:latest'
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
      - ./scripts/schema_creation_psql.sql:/docker-entrypoint-initdb.d/schema_creation_psql.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "echo 'Running healthcheck for Postgres: pg_isready -d $${POSTGRES_DB}' && pg_isready -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 30s
      retries: 5
    networks:
      - db

  db-ui:
    image: 'dpage/pgadmin4:latest'
    container_name: pgAdmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "${POSTGRES_USER}@domain.com"
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - db
    volumes:
      - db-ui:/var/lib/pgadmin

  web:
    container_name: streamlit_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db
    environment:
      SNOW_ACCOUNT: ${SNOW_ACCOUNT}
      SNOW_AUTOCOMMIT: ${SNOW_AUTOCOMMIT}
      SNOW_DATABASE: ${SNOW_DATABASE}
      SNOW_SCHEMA: ${SNOW_SCHEMA}
      SNOW_WAREHOUSE: ${SNOW_WAREHOUSE}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      SNOW_USER_TESTING: ${SNOW_USER_TESTING}
      SNOW_PASSWORD_TESTING: ${SNOW_PASSWORD_TESTING}

networks:
  db:
    driver: bridge

volumes:
  db:
  db-ui: