services:

  db:
    image: 'postgres:latest'
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
      - ./scripts/schema_creation_psql.sql:/docker-entrypoint-initdb.d/schema_creation_psql.sql
    ports:
      - "5432:5432"
    networks:
      - db

  web:
    container_name: streamlit_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db
    environment:
      POSTGRES_HOST: db

networks:
  db:
    driver: bridge

volumes:
  db: