version: '3.8'

services:

  db:
    image: 'postgres:latest'
    container_name: postgress
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
      - ./scripts/schema_creation_psql.sql:/docker-entrypoint-initdb.d/schema_creation_psql.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - db

  web:
    container_name: streamlit_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db: