CREATE OR REPLACE SCHEMA imdb_dwh;
USE SCHEMA imdb_dwh;

CREATE OR REPLACE TABLE dim_genres(
    GENRE_ID INT PRIMARY KEY,
    GENRE_NAME VARCHAR(10) NOT NULL
);

CREATE OR REPLACE TABLE dim_actors(
    ACTOR_ID INT PRIMARY KEY,
    ACTOR_NAME VARCHAR(50) NOT NULL
);

CREATE OR REPLACE TABLE dim_directors(
    DIRECTOR_ID INT PRIMARY KEY,
    DIRECTOR_NAME VARCHAR(50) NOT NULL
);

CREATE OR REPLACE TABLE dim_years(
    YEAR_ID INT PRIMARY KEY, 
    YEAR INT NOT NULL
);

CREATE OR REPLACE TABLE bridge_genres(
    BRIDGE_GENRE_ID INT PRIMARY KEY,
    FILM_RANK INT NOT NULL,
    GENRE_ID INT NOT NULL
);

CREATE OR REPLACE TABLE bridge_actors(
    BRIDGE_ACTOR_ID INT PRIMARY KEY,
    FILM_RANK INT NOT NULL,
    ACTOR_ID INT NOT NULL
);

CREATE OR REPLACE TABLE fact_table(
    FILM_RANK INT PRIMARY KEY,
    BRIDGE_GENRE_ID INT NOT NULL,
    BRIDGE_ACTOR_ID INT NOT NULL,
    DIRECTOR_ID INT NOT NULL,
    YEAR_ID INT NOT NULL,

    RUNTIME INT NOT NULL,
    REVENUE FLOAT NOT NULL,
    USER_VOTES INT NOT NULL,
    USER_SCORE INT NOT NULL,
    CRITIC_SCORE INT NOT NULL,

    RUNTIME_CATEGORY VARCHAR(6) NOT NULL,
    REVENUE_CATEGORY VARCHAR(6) NOT NULL,
    USER_VOTES_CATEGORY VARCHAR(6) NOT NULL,
    USER_SCORE_CATEGORY VARCHAR(30) NOT NULL,
    CRITIC_SCORE_CATEGORY VARCHAR(30) NOT NULL,

    FOREIGN KEY(BRIDGE_GENRE_ID) REFERENCES bridge_genres(bridge_genre_id),
    FOREIGN KEY(BRIDGE_ACTOR_ID) REFERENCES bridge_actors(bridge_actor_id),
    FOREIGN KEY(DIRECTOR_ID) REFERENCES dim_directors(director_id),
    FOREIGN KEY(YEAR_ID) REFERENCES dim_years(year_id)
);
