\c practice_datasets;
SET client_encoding = 'UTF8';

-- Drop schema if it exists (cascade to delete all content)
DROP SCHEMA IF EXISTS imdb_dwh CASCADE;

-- Create schema
CREATE SCHEMA imdb_dwh;
SET search_path TO imdb_dwh;

-- Create tables
CREATE TABLE dim_genres(
    GENRE_ID INT PRIMARY KEY,
    GENRE_NAME VARCHAR(10) NOT NULL
);

CREATE TABLE dim_actors(
    ACTOR_ID INT PRIMARY KEY,
    ACTOR_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE dim_directors(
    DIRECTOR_ID INT PRIMARY KEY,
    DIRECTOR_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE dim_years(
    YEAR_ID INT PRIMARY KEY, 
    YEAR INT NOT NULL
);

CREATE TABLE bridge_genres(
    BRIDGE_GENRE_ID INT PRIMARY KEY,
    FILM_RANK INT NOT NULL,
    GENRE_ID INT NOT NULL
);

CREATE TABLE bridge_actors(
    BRIDGE_ACTOR_ID INT PRIMARY KEY,
    FILM_RANK INT NOT NULL,
    ACTOR_ID INT NOT NULL
);

CREATE TABLE fact_table(
    FILM_RANK INT PRIMARY KEY,
    BRIDGE_GENRE_ID INT NOT NULL,
    BRIDGE_ACTOR_ID INT NOT NULL,
    DIRECTOR_ID INT NOT NULL,
    YEAR_ID INT NOT NULL,

    RUNTIME INT NOT NULL,
    REVENUE FLOAT NOT NULL,
    USER_VOTES INT NOT NULL,
    USER_SCORE INT NOT NULL,
    CRITIC_SCORE INT NOT NULL,

    RUNTIME_CATEGORY VARCHAR(6) NOT NULL,
    REVENUE_CATEGORY VARCHAR(6) NOT NULL,
    USER_VOTES_CATEGORY VARCHAR(6) NOT NULL,
    USER_SCORE_CATEGORY VARCHAR(30) NOT NULL,
    CRITIC_SCORE_CATEGORY VARCHAR(30) NOT NULL,

    FOREIGN KEY(BRIDGE_GENRE_ID) REFERENCES bridge_genres(BRIDGE_GENRE_ID),
    FOREIGN KEY(BRIDGE_ACTOR_ID) REFERENCES bridge_actors(BRIDGE_ACTOR_ID),
    FOREIGN KEY(DIRECTOR_ID) REFERENCES dim_directors(DIRECTOR_ID),
    FOREIGN KEY(YEAR_ID) REFERENCES dim_years(YEAR_ID)
);